# Всё это хранится в таком виде только для задания
common_john_brewing_co_manchester_actual_json = {
    "id": "common-john-brewing-co-manchester",
    "name": "Common John Brewing Co",
    "brewery_type": "planning",
    "street": None,
    "address_2": None,
    "address_3": None,
    "city": "Manchester",
    "state": "Tennessee",
    "county_province": None,
    "postal_code": "37355-6064",
    "country": "United States",
    "longitude": None,
    "latitude": None,
    "phone": "9314090630",
    "website_url": "http://www.commonjohnbc.com",
    "updated_at": "2021-10-23T02:24:55.243Z",
    "created_at": "2021-10-23T02:24:55.243Z"
}

breweries_names = [
    'banjo-brewing-fayetteville',
    'barrel-brothers-brewing-company-windsor',
    'bay-brewing-company-miami',
    'bent-shovel-brewing-oregon-city',
    'snow-belt-brew-chardon',
    'boring-brewing-co-llc-boring',
    'brubakers-brewery-and-pub-sylvania',
    'camino-brewing-co-llc-san-jose',
    'cape-ann-lanes-gloucester',
    'center-pivot-quinter',
    'cerveceria-del-pueblo-pasadena',
    'circle-9-brewing-san-dieg',  # ошибка внесена умышленно, верный поинт 'circle-9-brewing-san-diego'
    'cerveza-guajira-miami',
    'common-john-brewing-co-manchester',
    'corner-pub-reedsburg',
    'cyclers-brewing-montgomer',  # ошибка внесена умышленно, верный поинт 'cyclers-brewing-montgomery'
    'dented-face-brewing-company-delta',
    'dfamle-enterprises-lp-dba-four-sons-brewing-huntington-beach',
    'devout-brewing-export',
    'dirt-road-brewing-corvallis',
]
cityes_names = [
    'Fayetteville',
    'Windsor',
    'Miami',
    'Oregon City',
    'Chardon',
    'Boring',
    'Sylvania',
    'San Jose',
    'Gloucester',
    'Quinter',
    'Pasadena',
    'San Diego',
    'Miami',
    'Manchester',
    'Reedsburg',
    'Montgomery',
    'Delta',
    'Huntington Beach',
    'Export',
    'Corvallis'
]

postal_code = [
    '25840',
    '95492-6652',
    '33130-3488',
    '97045-9453',
    '44024',
    '97009',
    '43560-9586',
    '95113',
    '01930-2256',
    '67752',
    '91105-1822',
    '92111-2223',
    '33137',
    '37355-6064',
    '53959-1967',
    '77356',
    '81416',
    '92648-1235',
    '15632',
    '97330-3005'
]
